### ISSUE TITLE
TSL2561, i2c transaction seemed to be stopped too soon

### ISSUE THREAD

**Issue by sdalu** [apache/mynewt-core#1001]
Reading code, I2C transaction seemed to be marked as finished to soon during the register read.
Would have expected 0 for the last parameter (like what is done in mpu6050)

https://github.com/apache/mynewt-core/blob/b91942a8b5d269c5da403a40cddd9cb3b3a59e5d/hw/drivers/sensors/tsl2561/src/tsl2561.c#L141-L142

https://github.com/apache/mynewt-core/blob/b91942a8b5d269c5da403a40cddd9cb3b3a59e5d/hw/drivers/sensors/tsl2561/src/tsl2561.c#L175-L176

**Comment by sterlinghughes** [comment]
why closed?

**Comment by sdalu** [comment]
There was some unrelated talk on i2c on slack, and I'm not sure that's really an issue and not a misunderstanding of my part.
