### ISSUE TITLE
more than 31 bytes in advertsing and scanning

### ISSUE THREAD

**Issue by swapkada** [apache/mynewt-core#1027]
hello, I am using btshell and trying to send more than 31 bytes but not able to send. it shows invalid mfg_data.. but if I put less than 31 bytes in mfg_data it accepts. is there any alternative way to send more than 31 bytes?  is there anything which I am missing?
Thank you in advance

**Comment by SharanIoT** [comment]
@swapkada Advertising or Scan Response data length is max 31 Octets as per the Bluetooth Core Spec 4.2

**Comment by sjanc** [comment]
Hi,

You can use Advertising Extensions which allows for up to 1650 bytes of data. Check BLE_EXT_ADV and BLE_EXT_ADV_MAX_SIZE syscfg values.

You need scanner that supports extended advertising to be able to see those, NimBLE supports it. Also some latest top Android Phones (eg Sony Xperia XZ2) support those.
