### ISSUE TITLE
bsp/nrf52840pdk: uart1 should be hardware instead of bitbang

### ISSUE THREAD

**Issue by sdalu** [apache/mynewt-core#1043]
nRF52840 has 2 uart unit available, but the board is using hardware uart for uart0 and bitbang for uart1

**Comment by wes3** [comment]
I thought I had changed this but I now realize that I did not submit a PR for this; I changed this in a different repo but did not add it to mynewt-core. This should definitely be changed.

**Comment by mlaz** [comment]
Is this happening for any reason? @sterlinghughes @wes3

**Comment by wes3** [comment]
is what happening for any reason? Not sure what you are asking...
