### ISSUE TITLE
blemesh: generic level functionality doesn't work

### ISSUE THREAD

**Issue by SharanIoT** [apache/mynewt-core#1095]
Hi,

I'm trying to test blemesh sample using SiLabs Android App. The generic on/off model work fine but generic level. I don't see any generic level set events. 

Is it a blemesh issue or the SiLabs App's?

**Comment by rymanluk** [comment]
Hi,

On Wed, 16 May 2018 at 10:20, Sharan Avati <notifications@github.com> wrote:

> Hi,
>
> I'm trying to test blemesh sample using SiLabs Android App. The generic
> on/off model work fine but generic level. I don't see any generic level set
> events.
>
> Is it a blemesh issue or the SiLabs App's?
>

This is SiLabs issue but we have workaround for this and application
recently merged: https://github.com/apache/mynewt-core/pull/1063

\Łukasz
