### ISSUE TITLE
Can't write data to characteristic

### ISSUE THREAD

**Issue by kartik9k** [apache/mynewt-core#1118]
Hi all! I've been trying to write data in the characteristic of a service from central module, using a modified version of blecent example. The `peer_chr_find_uuid` returns a non NULL value which means that the characteristic of the service is successfully discovered. 

The `ble_gattc_write_flat` also returns no error code but the `gatt_svr_chr_access_sec_test` (which is the callback for this characteristic) is never called for the characteristic in the peripheral and hence I'm unable to read the data sent from the central module.

If anyone has any insights please share?

TIA! :D

**Comment by andrzej-kaczmarek** [comment]
I assume peripheral is running `bleprph` app so characteristic you're trying to write requires connection to be encrypted for this and write fails. No error code for `ble_gattc_write_flat` means only that write request/command was txed successfully but you should get a callback on write complete with error code. If the error code is e.g. `BLE_ATT_ERR_INSUFFICIENT_ENC` you should initiate pairing and then retry write once encryption was enabled on link (there will be GAP event for this).

**Comment by ccollins476ad** [comment]
One of the two peers needs to initiate the GAP encryption procedure.  In Nimble, this is done by calling `ble_gap_security_initiate()` (https://mynewt.apache.org/network/ble/ble_hs/ble_gap/functions/ble_gap_security_initiate/).

Your central app can do this immediately upon connecting.  Another common solution is to initiate security whenever your callback reports the `BLE_ATT_ERR_INSUFFICIENT_AUTHEN` error.
