### ISSUE TITLE
Creating multiple encrypted connections

### ISSUE THREAD

**Issue by kartik9k** [apache/mynewt-core#1123]
Hi all! I want to write to multiple peripherals from a central module for which it was pointed out that the connection needs to be encrypted. So as advised, I used the `ble_gap_security_initiate` for initiating encryption and it worked perfectly for one connection. However, I'm having multiple connections and I want to write to all of them, and hence `ble_gap_security_initiate` is giving an error `BLE_HS_ENOMEM` after the first connection. (Data is successfully sent to 1 peripheral but not to others as the write callback is giving `BLE_ATT_ERR_INSUFFICIENT_AUTHEN`)

Can anyone help me on this?

TIA! :D

**Comment by sjanc** [comment]
Try setting BLE_SM_MAX_PROCS=2 for your application
