### ISSUE TITLE
Weird documentation concerning tu_init()

### ISSUE THREAD

**Issue by BeckmaR** [apache/mynewt-core#1225]
The [documentation](https://mynewt.apache.org/latest/os/modules/testutil/tu_init/) mentions to use `tu_init()` to initialize the test, which however produces a compiling error. Turns out `tu_init()` isn't actually API but automatically called by `sysinit()`:

```
void
tu_init(void)
{
    /* Ensure this function only gets called by sysinit. */
    SYSINIT_ASSERT_ACTIVE();

#if MYNEWT_VAL(SELFTEST)
    os_init(NULL);
    ts_config.ts_print_results = 1;
#endif
}
```

While `tu_init()` actually exists, the `struct tu_config`, mentioned in the same doc, does not.

**Comment by ccollins476ad** [comment]
Thanks, @BeckmaR.  The testutil documentation was indeed quite out of date.  I have submitted https://github.com/apache/mynewt-core/pull/1276 which updates the testutil documentation.
