### ISSUE TITLE
In the bootloader, deinitialise all activated peripherals before jumping to main app

### ISSUE THREAD

**Issue by amrbekhit** [apache/mynewt-core#1264]
Following on from [this mailing list thread](https://lists.apache.org/thread.html/c8cb49947625af476612b79b3c1a1e5db31fa52c75132ffb63dc81e5@%3Cdev.mynewt.apache.org%3E), any peripherals turned on in the bootloader remain on after the main app has started executed, causing unexpectedly high power consumption. I think it would be a good idea for the bootloader to de-initialise any initialised peripherals before jumping the main app. This would allow the main app to start from a blank slate and removes the need to add any de-initialisation code to it (which would require knowing what the bootloader has initialised).

**Comment by sjanc** [comment]
Since we deleted bootloader from core and moved to mcuboot I think this can be closed (and tracked in mcuboot instead if relevant)
