### ISSUE TITLE
Program retention in Redbear Nano 2

### ISSUE THREAD

**Issue by kartik9k** [apache/mynewt-core#1303]
I created a custom PCB for a project recently, it works fine when the code is uploaded. It has a switch with which I can turn the battery connection on and off for the MB-N2. But when it switched off, it somehow resets the uploaded code. 

We're using XTAL_32768_SYNTH instead of XTAL_32768 as we don't have the latter in our PCB due to space constraints. 

Is the code retention problem somehow related to the clock that we're using or due to any other known reason?

Thanks in advance!

**Comment by wes3** [comment]
Hello kartik. Could you please provide a bit more information here? How are you uploading the code? Depending on how you are doing this you have to "confirm" the image after it boots into the new image. If you do not, the previous image will get loaded. I suspect that this is what you are seeing.

**Comment by kartik9k** [comment]
I'm programming my modules using command line instructions for Mynewt OS.

For eg: ```newt load <name-of-module>```

So apparently, when I re-upload the bootloader, the last program starts executing. I guess the program is stored in the flash correctly but the bootloader gets refreshed.

Any insights?

**Comment by wes3** [comment]
I am sorry; I am not following what you are saying. Why are you re-flashing the bootloader btw? You should only need to do that once. You should be able to verify that the code you have loaded is the image you are attempting to load. Are you saying that the device simply resets?

**Comment by kartik9k** [comment]
Yes! Whenever it is switched on, it resets.

On burning the bootloader again, the device starts running the last program that was flashed.

**Comment by wes3** [comment]
So this all sounds like normal operation to me. Re-flashing the bootloader will not erase the currently loaded image so I would expect it to boot the last image you loaded via newt load. Not sure what you mean by "...whenever it is switched on, it resets". Are you on the mynewt slack? I think it is better to have a chat session if you are still thinking something is wrong.

**Comment by adityaxavier** [comment]
Hi, I think the problem is with DC-DC configuration. I had similar problems with mine, Firmware would only boot on first flash and wouldn't after restart. If your board doesn't have DC-DC available, switch it off from the BSP, and rebuild everything again.
