### ISSUE TITLE
fs: nffs: during inode update the file name might be corrupted

### ISSUE THREAD

**Issue by nvlsianpu** [apache/mynewt-core#1397]
While inode is updated it is possible that Garbage Collection
is called which caused overwrite of inode's filename as the same
buffer was used to keep the filename and copping data in GC.

bug was spoted in zephyr copy of nffs: https://github.com/zephyrproject-rtos/zephyr/issues/9749

Patch is here: https://github.com/apache/mynewt-nffs/pull/9

**Comment by mlaz** [comment]
Fixed and merged on https://github.com/apache/mynewt-nffs/pull/9
