### ISSUE TITLE
Incorrect SPI Configuration Syscfg's for MCU_NRF52832 and MCU_NRF52840 

### ISSUE THREAD

**Issue by jeremywood** [apache/mynewt-core#1455]
The nRF52832 has 3 SPI controllers, and the nRF52840 has 4. Mynewt only allows you to configure SPI0-1 for the nRF52832 and SPI1-2 for the nRF52840.

**Comment by jeremywood** [comment]
I'm addressed this with PR #1456.

**Comment by andrzej-kaczmarek** [comment]
fixed in #1456
