### ISSUE TITLE
nrf51xxx/hal_uart: Missing baud rates

### ISSUE THREAD

**Issue by tyszja** [apache/mynewt-core#1579]
Baud rates of 1200, 2400, 4800, 14400, 28800, 31250, 56000, 76800, 250000 which are present in ``nrf51_bitfields.h`` are not supported in HAL's ``hal_uart_baudrate(...)``. It seems that nrf52's HAL misses a few as well.

**Comment by mlaz** [comment]
Fixed on https://github.com/apache/mynewt-core/pull/1671
