### ISSUE TITLE
gdb-arm-none-eabi not found

### ISSUE THREAD

**Issue by tcpipchip** [apache/mynewt-core#1650]
After a 
sudo apt-get install gdb-arm-none-eabi
got
E: Unable to locate package gdb-arm-none-eabi
can you help me ?

**Comment by tcpipchip** [comment]
solved. Need to find the bin code from a repository and write it to /dev/bin

**Comment by Dreamfantcy** [comment]
how to get bin code? please!

**Comment by tcpipchip** [comment]
Please, see my blog (portuguese)

I report how to solve that

https://mynewt-ninabx.blogspot.com/2019/02/programando-nina-b112-com-apache-mynewt.html
