### ISSUE TITLE
bsp/dwm1001-dev: spi pin assignement

### ISSUE THREAD

**Issue by sdalu** [apache/mynewt-core#1657]
Was there a reason to move pin assignement from SPI_1 to SPI_0 and remove SPI_1 in 
https://github.com/apache/mynewt-core/commit/4e32f9d080d707d70d42a69cf522f98c7a570201

SPI_0 was initially configured with default values to interface with dw1000 (pin 16,20,18) present in the dw1001 module.
Can we revert back to what it was?

**Comment by andrzej-kaczmarek** [comment]
the reason was copy&paste so it's ok to configure them as they should be

**Comment by sdalu** [comment]
ok, created https://github.com/apache/mynewt-core/pull/1658 to revert to default configuration.

**Comment by sdalu** [comment]
merged
