### ISSUE TITLE
Compile error on Mac Mojave

### ISSUE THREAD

**Issue by charuwalee** [apache/mynewt-core#1685]
Hi,

I've tried to install mynewt on Mac Mojave version 10.14.3. Every went well until I tried to create a new project. I followed the instructions from https://mynewt.apache.org/latest/get_started/project_create.html and got tens of error messages when I tried to test the project package by using command `newt test @apache-mynewt-core/sys/config`. The snapshot of an example of error messages are as shown in the pictures below.

<img width="1310" alt="Screen Shot 2562-03-13 at 14 59 10" src="https://user-images.githubusercontent.com/22586036/54262388-a1042c80-45a0-11e9-9d53-e2eecb4a1670.png">

<img width="1314" alt="Screen Shot 2562-03-13 at 15 07 12" src="https://user-images.githubusercontent.com/22586036/54262801-c180b680-45a1-11e9-9394-023c52cc7ae7.png">

Could anyone give a hint of what went wrong and how to fix this?

Thank you in advance!!
Charuwalee

**Comment by sjanc** [comment]
Hi,

You need to use Xcode 9,  I think this is related to deprecation of 32bit binaries (and newt test is using native target which is 32bit)

**Comment by sterlinghughes** [comment]
I think we need to keep this open and fix it, a Mojave install breaks newt sim, which most of the docs suggest using.  Also, it's complicated to move back to Xcode 9 and we should at least have instructions to do so.

Also, I'm wondering if we shouldn't take this oppty to use QEMU, or run 32-bit in QEMU.  The support for STM32* etc is there, but pretty weak (and not distributed in homebrew binaries), but we could look at emulating a X86 system by default and running sim in there?

**Comment by sjanc** [comment]
fixed in master
