### ISSUE TITLE
Simplify *-core, and breakout repos

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-core#1695]
Core contains functionality that should be broken into it's own repos, or is duplicative of information that is already broken into separate repos, this includes: 

- apps/*: many of the apps are ble, or otherwise related and those should be in the various repos themselves.

- boot/*: this is superseded by mcuboot

- mgmt/*: this is superseded by mcumgr

- net/
  - nimble is already moved to mynewt-nimble, but we should finally force the simlinks
  - lorawan should be merged with mynewt-lorawan
  - ip, mqtt, wifi should be their own mynewt-net (or mynewt-nip?) 

We should schedule all of this for the release of Mynewt 1.7, and do it after 1.6 is released.

**Comment by sjanc** [comment]
bootutil is now replaced by mcuboot
