### ISSUE TITLE
Nucleo 476, SPI communication stalles

### ISSUE THREAD

**Issue by kasjer** [apache/mynewt-core#1705]
When trying sensors from sensor_creator (with some configuration changes to make it build on nucleo) initial communication works, bme280 and spiflash are detected correctly.
Later when sensor shell was used to read bme280, communication was not working, chip select went down like expected but clock and data lines were dead.

**Comment by utzig** [comment]
F7 and F3 have the same SPI module, have you tried one of those to check if they fail similarly?

**Comment by kasjer** [comment]
I have only l476 board
