### ISSUE TITLE
Tutorial update - Use HCI access to NimBLE controller - HAL_UART_FLOW_CTL_NONE

### ISSUE THREAD

**Issue by bethjonesbluesky** [apache/mynewt-core#1747]
https://mynewt.apache.org/latest/tutorials/ble/blehci_project.html

Setting BLE_HCI_UART_FLOW_CTRL's value (nimble/transport/uart/syscfg.yml) to HAL_UART_FLOW_CTL_NONE is needed in the paragraph "If there is no CTS/RTS lines present in the test environment, flow control should be turned off. This can be done with -N option for btattach. Note: -N option came with BlueZ ver 5.44."

**Comment by aditihilbert** [comment]
Thanks for pointing this out! Would be very helpful if you could use the "Edit on GitHub" button in the top-right corner of the doc page to add this and generate a pull request. Thanks!

**Comment by bethjonesbluesky** [comment]
No problem, it's done.
