### ISSUE TITLE
sys/config test failed on Windows

### ISSUE THREAD

**Issue by damageg** [apache/mynewt-core#1925]
Following the install guide on Windows 10 (MSYS2 64 bit),  I created a first project and ran

newt test @apache-mynewt-core/sys/config

I got:
repos/apache-mynewt-core/hw/mcu/native/src/hal_uart.c:281:9: error: implicit declaration of function ‘openpty’; did you mean ‘openat’? [-Werror=implicit-function-declaration]
  281 |     if (openpty(&fd, &loop_slave, pty_name, NULL, NULL) < 0) {
      |         ^~~~~~~
      |         openat
cc1: all warnings being treated as errors

**Comment by damageg** [comment]
It's not supported on Windows - Doh.

**Comment by rajithavk** [comment]
Does it mean, mynewt is not supported for windows?
because the blinky starter project also fails with the same error.
