### ISSUE TITLE
Mynewt OS on Particle Xenon board

### ISSUE THREAD

**Issue by OTLabs** [apache/mynewt-core#1950]
Is it possible to run Mynewt OS on [Particle Xenon board](https://docs.particle.io/datasheets/mesh/xenon-datasheet/)?

**Comment by mlaz** [comment]
It is, however you would need a BSP (probably similar to adafruit nrf52 feather's) for that board and a JTAG adapter so you would be able to flash it.

**Comment by sjanc** [comment]
this board is discontinued now and unlikely to get upstream support
