### ISSUE TITLE
mac os mojave doesn't run sim

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-core#1960]
With apple breaking 32-bit support.  One easy solution for this is to map newt to use dockerized toolchain & run under 32-bit linux.  Instructions and toolchain support should be updated to use docker so we can still run simulated projects on Mac OS.

**Comment by mkiiskila** [comment]
Added more specific instructions regarding running unit tests (and sim) under docker with Mojave.
https://github.com/apache/mynewt-documentation/pull/80
