### ISSUE TITLE
Build failure due to implicit declaration of 'static_assert'

### ISSUE THREAD

**Issue by mehulhirpara** [apache/mynewt-core#2040]
Unable to build blemesh_light target on latest code (0-dev).

**Compilation Error**
`
Error: repos/apache-mynewt-core/kernel/os/src/os_mempool.c: In function 'os_memblock_from':
repos/apache-mynewt-core/kernel/os/src/os_mempool.c:308:5: error: implicit declaration of function 'static_assert' [-Werror=implicit-function-declaration]
     static_assert(sizeof block_addr == sizeof baddr32,
     ^
cc1: all warnings being treated as errors
`

**Target YML:**
`
target.app: "@apache-mynewt-nimble/apps/blemesh_light"
target.bsp: "@apache-mynewt-core/hw/bsp/nordic_pca10056"
target.build_profile: debug
`

**Syscfg YML:**
`
syscfg.vals:
    BLE_MESH_DEV_UUID: "(uint8_t[16]){0x22, 0x20, 0}"
    BLE_MESH_PB_GATT: 1
`

**Package YML:**
`
pkg.name: targets/blemesh_light
pkg.type: target
pkg.description: 
pkg.author: 
pkg.homepage: 
`

**Comment by andrzej-kaczmarek** [comment]
which compiler/version do you use? this builds fine with GCC

**Comment by mehulhirpara** [comment]
newt version
Apache Newt
   Version: 1.7.0
  Git Hash: unknown
Build Date: 2019-09-03_13:44

**Comment by mehulhirpara** [comment]
update:
with docker based newt, I am able to compile.

**Comment by deepthits** [comment]
What is the solution for this issue? Even I am facing this

**Comment by andrzej-kaczmarek** [comment]
imo we should change `static_assert` (C++ symbol) to `_Static_assert` (C11 symbol) - we anyway have `#define` to redefine the former to the latter. not sure if this will be supported by old GCC, but works fine in 7.x+.

**Comment by kasjer** [comment]
I would opt to change assert.h not to check compiler version when static_assert is defined.
It is mentioned in cppreference that convenience macro is defined for _Static_assert starting from C11 but it may be visible on gcc without C11.
Then if _Static_assert keyword is not present compilation will fail anyway.
```
#if !defined __cplusplus
#define static_assert _Static_assert
#endif
```
