### ISSUE TITLE
question of mynewt setup

### ISSUE THREAD

**Issue by li-yizhi** [apache/mynewt-core#2185]
I'm a beginner of mynewt. When I set up mynewt to this step [Use a newt wrapper script](http://mynewt.apache.org/latest/get_started/docker.html#use-a-newt-wrapper-script)
I confused:
1.The file's name is newt, what's it suffix name?

> Create the following file, name it newt

2.How to do this step?

> make it executable

3.What is /your path/ ? Docker's Installation path or any other path. 

> put it in your path

**Comment by utzig** [comment]
Those are all OS specific concepts that are not Mynewt related, which OS are you using?

**Comment by li-yizhi** [comment]
> Those are all OS specific concepts that are not Mynewt related, which OS are you using?

win 10

**Comment by cqexbesd** [comment]
The docs are written assuming a UNIX like environment. If you have the Linux subsystem for Windows 10 you could probably use them unmodified however I don’t have any experience with Windows 10 so I’m just guessing.

Assuming that the Linux subsystem will make your W10 machine behave like UNIX then:

1. No suffix is required
2. chmod a+x file
3. The path is the list of directories the shell looks for commands. How to set it depends on your shell but assuming you are using `bash` then `export PATH=${PATH}:/path/to/new/directory`

I would recommend having a read of some documentation about basic UNIX commands and the Linux subsystem though, as @utzig said, these aren’t mynewt concepts.

**Comment by li-yizhi** [comment]
> The docs are written assuming a UNIX like environment. If you have the Linux subsystem for Windows 10 you could probably use them unmodified however I don’t have any experience with Windows 10 so I’m just guessing.
> 
> Assuming that the Linux subsystem will make your W10 machine behave like UNIX then:
> 
> 1. No suffix is required
> 2. chmod a+x file
> 3. The path is the list of directories the shell looks for commands. How to set it depends on your shell but assuming you are using `bash` then `export PATH=${PATH}:/path/to/new/directory`
> 
> I would recommend having a read of some documentation about basic UNIX commands and the Linux subsystem though, as @utzig said, these aren’t mynewt concepts.

Thanks a lot! It's very helpful!
