### ISSUE TITLE
Could not resolve app package: @mcuboot/boot/mynewt

### ISSUE THREAD

**Issue by Thilanka97** [apache/mynewt-core#2189]
hey I am facing this problem with blinky project.
 _**Could not resolve app package: @mcuboot/boot/mynewt**_

 I tried _**newt upgrade -f**_  but I am getting following error with that cmd. 
_**Error: usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]**_

Also when I create the targets, inside the repo folder of the project the folders _"mcuboot" ,_ _"apache-mynewt-mcumgr"_ and _"apache-mynewt-nimble"_ folders are not created.

What is wrong here. I have already installed git as well.  Please help me to solve this problem. 

Thanks in advance!

**Comment by sjanc** [comment]
Hi,

which newt version and what OS do you use?

**Comment by utzig** [comment]
Check `git --version` and do `newt -ldebug upgrade -v` to get some debugging, but you probably need to upgrade `newt` due to some issue with submodules in mcuboot.

**Comment by w277277w** [comment]
HI，I had the same problem.
How did you solve the problem?

**Comment by sjanc** [comment]
is this stil an issue with 1.8 ?

**Comment by w277277w** [comment]
it is no issue with 1.8, It's wrong that the project upgrade without '--escape=false' on windows, thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Szymon Janc"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 晚上10:14
收件人: "apache/mynewt-core"<mynewt-core@noreply.github.com&gt;; 
抄送: "576057297"<576057297@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [apache/mynewt-core] Could not resolve app package: @mcuboot/boot/mynewt (#2189)





 
is this stil an issue with 1.8 ?

**Comment by sjanc** [comment]
great!
