### ISSUE TITLE
Put arduino_zero support into core

### ISSUE THREAD

**Issue by sjanc** [apache/mynewt-core#2236]
some time ago atmel relicenced their code available at http://packs.download.atmel.com/ to APL 2.0 which can now be included into Apache Mynewt core.

This should allow to deprecate need for https://github.com/runtimeinc/mynewt_arduino_zero

**Comment by sjanc** [comment]
are you working on this?

**Comment by mlaz** [comment]
I am, however some drivers have to be rewritten, since a good part of SERCOM hal integration was removed from the (now relicenced) sdk.

**Comment by sjanc** [comment]
@mlaz bump :) any progress on this?
