### ISSUE TITLE
LoRa with RFM95

### ISSUE THREAD

**Issue by danielkucera** [apache/mynewt-core#2354]
Hello,

I'm unable to join with RFM95 radio module. I defined my own BSP, tried both sx1276 and sx1272 drivers but without luck. The result is always the following:
```
400851 Attempting to join...
compat> Join cb. status=7 attempts=1
```
The same hardware works with mbed framework. 
The signal seems to be very week in comparison with mbed, See attached gqrx screenshots:
mynewt sx1272:
![Screenshot from 2020-08-16 20-10-16](https://user-images.githubusercontent.com/1734256/90341295-b2a3fc00-dffe-11ea-8138-7fc0e746c48e.png)

mynewt sx1276:
![Screenshot from 2020-08-16 20-18-03](https://user-images.githubusercontent.com/1734256/90341302-c0f21800-dffe-11ea-9a35-7d0e97cbb5fd.png)

mbed:
![Screenshot from 2020-08-16 20-20-20](https://user-images.githubusercontent.com/1734256/90341303-c6e7f900-dffe-11ea-8a67-0c2d6215de88.png)

**Comment by danielkucera** [comment]
I managed to fix the signal strength issue with:
```
SX1276_HF_USE_PA_BOOST: 1
```
![Screenshot from 2021-02-08 22-31-05](https://user-images.githubusercontent.com/1734256/107284954-c6d12f00-6a5e-11eb-8436-c3ec8f75a923.png)

But it is still not registering using `las_join 1`. I don't see any RX packets in my gateway. I'll keep investigating.

**Comment by danielkucera** [comment]
Ok, the last missing value to correctly connect to TTN was:
```
    LORA_NODE_PUBLIC_NWK: 1
```
so the final config is:
```
    SPI_0_MASTER: 1
    SPI_0_MASTER_PIN_SCK: 30
    SPI_0_MASTER_PIN_MOSI: 2
    SPI_0_MASTER_PIN_MISO: 3

    # repos/apache-mynewt-core/net/lora/node/include/node/lora_band.h
    LORA_NODE: 1
    LORA_NODE_REGION: 6
    LORA_MAC_TIMER_NUM: 0
    LORA_NODE_PUBLIC_NWK: 1

    # lora pins
    #SX1276
    SX1276_SPI_IDX: 0
    SX1276_SPI_CS_PIN: 29 # NSS?
    SX1276_HF_USE_PA_BOOST: 1
```
and pins in `bsp.h`:
```
#define SX1276_DIO0         (31)
#define SX1276_DIO1         (4)
#define SX1276_DIO2         (5)
#define SX1276_DIO3         (26)
#define SX1276_DIO4         (28)
#define SX1276_DIO5         (25)
#define SX1276_NRESET       (27)
```
But I have to say that the documentation is very poor. :-1:

**Comment by tcpipchip** [comment]
i am having the same ISSUE :(
![image](https://user-images.githubusercontent.com/11488460/201347941-95508288-9d12-4dd1-a244-1a1cc4354a69.png)

**Comment by danielkucera** [comment]
As I wrote, it is.

**Comment by tcpipchip** [comment]
i am getting a progresss here...
i was using SPI0...and software was on SPI1

**Comment by tcpipchip** [comment]
are you using wich processor? And do you created the bootloader and app ?
