### ISSUE TITLE
Priority violations

### ISSUE THREAD

**Issue by danielkucera** [apache/mynewt-core#2473]
Latest master fails to compile with throwing following error:
```
Building target targets/nrf52_boot
Error: Priority violations detected (Packages can only override settings defined by packages of lower priority):
    Package: @apache-mynewt-core/hw/mcu/nordic/nrf52xxx overriding setting: OS_TICKS_PER_SEC defined by @apache-mynewt-core/kernel/os

Setting history (newest -> oldest):
    OS_TICKS_PER_SEC: [@apache-mynewt-core/hw/mcu/nordic/nrf52xxx:128, @apache-mynewt-core/kernel/os:]
```
How do I fix this?

**Comment by andrzej-kaczmarek** [comment]
You need to use latest newt tool (see https://github.com/apache/mynewt-newt/pull/423).

**Comment by navan93** [comment]
By latest do you mean version 1.8.0? I alread have Apache Newt 1.8.0 / unknown / 2020-06-23_13:52. Still getting the same error as above.

**Comment by danielkucera** [comment]
1.8.0 seems to be not enough. A new release would be helpful.

**Comment by mlaz** [comment]
@danielkucera you need to be using master. BTW, @andrzej-kaczmarek maybe we could start tagging the PRs that break build with non-latest master and cross referencing PRs between core and newt, what do you think?

**Comment by sjanc** [comment]
we could, although general rule of thumb would be use tools from master when playing with core master branch (same goes for nimble repo)

**Comment by sjanc** [comment]
@danielkucera you may wanna check with 1.9-rc1  https://dist.apache.org/repos/dist/dev/mynewt/apache-mynewt-1.9.0/rc1/

**Comment by sjanc** [comment]
is this stil an issue with 1.9 ?

**Comment by danielkucera** [comment]
It seems yes but now I'm stuck on another error #2583

**Comment by sjanc** [comment]
reopen if needed
