### ISSUE TITLE
TUD_DFU_DESC_LEN is never defined

### ISSUE THREAD

**Issue by t3zeng** [apache/mynewt-core#2704]
There is a calculation for `CONFIG_TOTAL_LEN` inside `apache-mynewt-core/hw/usb/tinyusb/std_descriptors/src/std_descriptors.c` that makes use of `TUD_DFU_DESC_LEN` which doesn't seem to ever get defined anywhere.

**Comment by t3zeng** [comment]
`
#define CONFIG_TOTAL_LEN    (TUD_CONFIG_DESC_LEN + \
                             CFG_TUD_CDC * TUD_CDC_DESC_LEN + \
                             CFG_TUD_MSC * TUD_MSC_DESC_LEN + \
                             CFG_TUD_HID * TUD_HID_DESC_LEN + \
                             CFG_TUD_BTH * TUD_BTH_DESC_LEN + \
                             CFG_TUD_DFU * TUD_DFU_DESC_LEN(1) + \
                             0)`

**Comment by kasjer** [comment]
It is defined in usbd.h

**Comment by t3zeng** [comment]
Yep looks like that was my issue. Thanks!
