### ISSUE TITLE
macOS Monterey NEWT installation issue

### ISSUE THREAD

**Issue by BRUNO7878** [apache/mynewt-core#2840]
Hi , despite all efforts  following the newt web site I do not succeed in installing newt on my Mac Book pro with OS Monterey 12.3  or 12.4.
See attached capture to look at various attempts I did .
[Résultat de Terminal.txt](https://github.com/apache/mynewt-core/files/8715295/Resultat.de.Terminal.txt)

May I ask you for support ? 
What Do I do wrong ?
Thank you Bruno

**Comment by sjanc** [comment]
I suggest you try with binaries provided in download section: https://mynewt.apache.org/download/
