### ISSUE TITLE
Is there a .pdf documentation for  apache-mynewt?

### ISSUE THREAD

**Issue by ujur007** [apache/mynewt-core#2857]
I am working with Apache mynewt. It has quite good documentation but it is only online and moving from one tab to another is hectic.

Do you know is there a pdf version for the documentation?

**Comment by sjanc** [comment]
I don't think we have PDF documentation unfortunatelly

**Comment by sjanc** [comment]
@wpiet  please have a look at this in spare time

**Comment by sjanc** [comment]
Hi,

There is initial (experimental) PDF documentation available at https://mynewt.apache.org/documentation/

Currently there is one only for master branch, but we plan to drop it on next release and just keep with PDF documentation for released versions

**Comment by ujur007** [comment]
Thanks. Appreciate your efforts as it will help me to navigate through the API easily.
