### ISSUE TITLE
BUILD fail for nrf5340dk board Error: Could not resolve BSP package: @apache-mynewt-core/hw/bsp/nordic_pca10095

### ISSUE THREAD

**Issue by SatishSolankeEsp** [apache/mynewt-core#3110]
Hi 
I am trying to create the ble project with blehci , created two target for nrf5340dk
![image](https://github.com/apache/mynewt-core/assets/102321386/5158c4c5-3d2c-4df7-83f7-59d506a2ba0e)
but show the above error while building the target.

i could also see the couple of warning as below :
![image](https://github.com/apache/mynewt-core/assets/102321386/19d9178f-4f8b-4ae9-a0b8-ed00ea504c9a)

Please help to build project for nrf5340dk. I would like flash the mynewt ble controller on nrf via hci .

Thanks,
Satish

**Comment by sjanc** [comment]
Hi,

this looks like repositories are not installed,  did you run 'newt upgrade' ?  what does 'newt info' shows?

**Comment by SatishSolankeEsp** [comment]
![image](https://github.com/apache/mynewt-core/assets/102321386/b111376f-4555-4baf-959a-e228b53eb7b1)
![image](https://github.com/apache/mynewt-core/assets/102321386/b3ef7ba6-b29f-498c-bbf8-d58f19034b0c)
newt info and newt upgrade shows warning like above .

**Comment by sjanc** [comment]
looks like you are using very old version (1.4) of mynewt,  please get latest newt tool from https://mynewt.apache.org/download/ and than either create new project or adjust your project.yml to point to 1.9.0 and do newt upgrade

**Comment by SatishSolankeEsp** [comment]
![image](https://github.com/apache/mynewt-core/assets/102321386/f82fac83-0fe1-410b-85a4-c7338b296176)
I Have change newt to 1.10.0 and still not able to build shows above errors .

I am not able to create new project show below error 
![image](https://github.com/apache/mynewt-core/assets/102321386/bec19690-f145-4ba3-9514-eb3a916b09a9)

**Comment by sjanc** [comment]
newt 1.10 had a bug, so either use newt 1.11 or try 'newt new --shallow=0 sniffproj'

as for unknown gcc option, you probably need to upgrade your toolchain

**Comment by SatishSolankeEsp** [comment]
I switch back to newt 1.9.0 works fine able to create new proj.
Build shows new error now:
![image](https://github.com/apache/mynewt-core/assets/102321386/7c9299e8-0410-4a1e-8840-8bd0caf77b14)

for gcc error i will check how to upgrade toolchain
![image](https://github.com/apache/mynewt-core/assets/102321386/9afebf6d-6010-4a97-af2f-a07de77278ef)

**Comment by sjanc** [comment]
I strongly suggest to test with newt 1.11, there were a lot of nrf53 related improvements in latest releases

As for ARM GCC update, you can either update ubuntu (18.04 is quite old...) or download one from ARm directly https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads   (I suggest using GCC 12 as 13 may give you some compilation warning we haven't fix yet)


Also, you may want to check cwiki for nRF53 on Mynewt: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=177047756   (and I'd recommend to use NRF5340_EMBED_NET_CORE:1 option instead of building own netcore image)

**Comment by sjanc** [comment]
Hi,  is this stil an issue?
