### ISSUE TITLE
在 ./build.sh后报如下错误

### ISSUE THREAD

**Issue by qiuchengkai** [apache/mynewt-core#3127]
15141@qiu UCRT64 ~/mynewt-newt-mynewt_1_3_0_tag
$ ./build.sh
./build.sh: line 30: go: command not found
* Error: could not extract go version (version string: )

15141@qiu UCRT64 ~/mynewt-newt-mynewt_1_3_0_tag

**Comment by sjanc** [comment]
You need Go setup to build newt tool from sources (https://golang.org/) 

Although I'd suggest to simply use binary releases from https://mynewt.apache.org/download/
There are new binary builds for linux, windows and mac

PS I'd strongly suggest to use something newer than 1.3 release
