### ISSUE TITLE
Issues when building for NRF52810

### ISSUE THREAD

**Issue by alvarop** [apache/mynewt-core#845]
I think I might have found a bug with the new nrfx stuff. If you try using the nrf52810 or nrf52840, you'd have to add '-DNRF52810_XXAA' on the bsp's pkg.yml instead of the old '-DNRF52'

Now when I build something, I get some definition collisions since many of the bsp's still use #include <nrf52.h> which, if I understand correctly, now should be #include <nrf.h>
So both get included and things get redefined, unless I'm doing something wrong.

There's also hw/mcu/nordic/nrf52xxx/include/mcu/cortex_m4.h, which has an include for NRF52840_XXAA, but otherwise defaults to nrf52.h

hw/drivers/nimble/nrf52/src/ble_hw.c includes nrf52_bitfields.h, which also breaks. I see nrf.h includes the appropriate ones for that too, so replacing it should be fine.

**Comment by mlaz** [comment]
https://github.com/apache/mynewt-core/pull/1106 was merged, this issue is resolved.
