### ISSUE TITLE
JSON library's array count not incrementing

### ISSUE THREAD

**Issue by adityaxavier** [apache/mynewt-core#864]
Firstly, there is almost no documentation regarding json utilization.

After following the example and documentation of mJSON which is not entirely the same as mynewt's JSON library. I was able to get the code working partially.

Which this code, am getting the following output

`000001 Buffer Initiated 
000002 JSON Read 0! 
000003 PRN = 10, elevation = 45, azimuth = 196 
Complete
`
[blinky.zip](https://github.com/apache/mynewt-core/files/1771077/blinky.zip)

**Comment by michal-narajowski** [comment]
Hi @adityaxavier,

I found some issues with your code and an issue in JSON library code. I submitted a pull request here: https://github.com/apache/mynewt-core/pull/884

The updated app code that should work fine can be found on my branch: 
https://github.com/michal-narajowski/incubator-mynewt-core/tree/json-fix-app

Best regards,
Michał Narajowski

**Comment by michal-narajowski** [comment]
@adityaxavier, does this solve your issue?

**Comment by adityaxavier** [comment]
@michal-narajowski, Yes it does..
