### ISSUE TITLE
shell/console locks with too much input

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-core#875]
1. Too many lines of input at a time locks it up.
2. If input is coming in faster than it's getting drained, console echo ends in endless wait.

**Comment by rymanluk** [comment]
@andrzej-kaczmarek  I have feeling you have some solution on this under testing, right?

**Comment by andrzej-kaczmarek** [comment]
does this still happen on latest master? iirc we made a workaround for this, i.e. detect this condition and just drop echoed characters to avoid deadlock.

anyway, I made a patch some time ago which allows to move handling of UART RX to task context so deadlock won't occur, here's PR with these changes: #894.

**Comment by sjanc** [comment]
This is fixed now.
