### ISSUE TITLE
Full MCU implementation on STM32F7

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-core#927]
It would be great to have complete HAL for the STM32F7, including SPI and working I2C.

**Comment by utzig** [comment]
SPI is *almost* there for in a single driver for all stm32 MCUs...

**Comment by utzig** [comment]
This can be closed once #1003, #1032 and #1039 are merged. Afterwards the following limitations deserve new issues:

1) I2C support for STM32F1
2) SPI slave support for STM32F3/STM32F7

**Comment by mlaz** [comment]
All the 3 PRs are merged.
