### ISSUE TITLE
README in net/nimble

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-core#956]
We should have a README in mynewt-core/net/nimble so that people who are confused by there being no code in there, know to look at mynewt-nimble.

**Comment by simonratner** [comment]
Also, perhaps link to the new repo from `mynewt-core/README` (replacing link to `mynewt-core/net/nimble`)?

**Comment by sjanc** [comment]
https://github.com/apache/mynewt-core/pull/1094
